//
//  ASFTableViewPublicGlobals.h
//  Patient Care
//
//  Created by Asif Mujteba on 01/02/2014.
//  Copyright (c) 2014 Asif Mujteba. All rights reserved.
//

// 版权属于原作者
// http://code4app.com (cn) http://code4app.net (en)
// 发布代码于最专业的源码分享网站: Code4App.com

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const kASF_OPTION_BACKGROUND;
FOUNDATION_EXPORT NSString *const kASF_OPTION_CELL_BACKGROUND;
FOUNDATION_EXPORT NSString *const kASF_OPTION_CELL_BORDER_COLOR;
FOUNDATION_EXPORT NSString *const kASF_OPTION_CELL_BORDER_SIZE;
FOUNDATION_EXPORT NSString *const kASF_OPTION_CELL_PADDING;
FOUNDATION_EXPORT NSString *const kASF_OPTION_CELL_TEXT_FONT_SIZE;
FOUNDATION_EXPORT NSString *const kASF_OPTION_CELL_TEXT_FONT_BOLD;
FOUNDATION_EXPORT NSString *const kASF_OPTION_CELL_TEXT_COLOR;
FOUNDATION_EXPORT NSString *const kASF_OPTION_CELL_TEXT_ALIGNMENT;

FOUNDATION_EXPORT NSString *const kASF_ROW_ID;
FOUNDATION_EXPORT NSString *const kASF_INNER_ROW_WEIGHTS;
FOUNDATION_EXPORT NSString *const kASF_ROW_CELLS;
FOUNDATION_EXPORT NSString *const kASF_ROW_OPTIONS;

FOUNDATION_EXPORT NSString *const kASF_IS_INNER_ROW;

FOUNDATION_EXPORT NSString *const kASF_CELL_TITLE;
FOUNDATION_EXPORT NSString *const kASF_CELL_IS_EDITABLE;
FOUNDATION_EXPORT NSString *const kASF_CELL_TEXTVIEW_DELEGATE;
FOUNDATION_EXPORT NSString *const kASF_CELL_TEXTVIEW_TAG;
FOUNDATION_EXPORT NSString *const kASF_CELL_IS_KEY;

@interface ASFTableViewPublicGlobals : NSObject

@end
